version: '3'
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      FLASK_APP: runner.py
      FLASK_ENV: development
      SECRET_KEY: test_key
      SQLALCHEMY_DATABASE_URI: mysql://root:password@localhost/flask_app_db
      REDIS_URL: redis://redis:6379/0

  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask_app_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

volumes:
  db_data:
