"""removed non using fields in address table.

Revision ID: 4598f43b7a66
Revises: b380ff49f1bd
Create Date: 2023-08-26 15:56:55.404456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4598f43b7a66'
down_revision = 'b380ff49f1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('street')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=200), nullable=False))
        batch_op.add_column(sa.Column('country', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=100), nullable=False))

    # ### end Alembic commands ###
