"""city is unique

Revision ID: 49650d854b83
Revises: 307ae50deaac
Create Date: 2023-08-26 16:13:26.241614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49650d854b83'
down_revision = '307ae50deaac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=100),
               nullable=True)
        batch_op.drop_index('id')
        batch_op.create_unique_constraint(None, ['city'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('id', ['id'], unique=False)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=100),
               nullable=False)

    # ### end Alembic commands ###
